export const RESET_ALL_INFO = 'RESET_ALL_INFO';
export const SET_SOCKET = 'SET_SOCKET';
export const UPDATE_MEETING_INFO = 'UPDATE_MEETING_INFO';
export const ADD_PARTICIPANT_INFO = 'ADD_PARTICIPANT_INFO';
export const REMOVE_PARTICIPANT_INFO = 'REMOVE_PARTICIPANT_INFO';